# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package.json pnpm-lock.yaml ./

# Install dependencies without running scripts to speed up install
RUN npm install --ignore-scripts

# Copy the rest of the application code
COPY . .

# Build the TypeScript code and ensure the entry file is executable
RUN npx tsc && chmod 755 build/index.js

# Expose standard I/O for MCP communication
CMD ["node", "build/index.js"]
